package RandomDataProgect;

public enum Events {
    GSTR3B_UPLOAD,

    GSTR3B_AUTOPOPULATE_PR,
    GSTR3B_AUTOPOPULATE_2B,
    GSTR3B_AUTOPOPULATE_RECON,
    GSTR3B_CONFIGURATION,
    GSTR3B_SAVE_AS_DRAFT,
    GSTR3B_SAVE_TO_GSTN,
    GSTR3B_OFFSET_LIAB,
    GSTR3B_CHALLAN,
    GSTR3B_ESIGN_DSC,
    GSTR3B_ESIGN_EVC,
    GSTR3B_FILE
}
